version: "3.9"
services:
  app:
    image: kayak-web
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - couchdb
    ports:
      - "12321:80"
  couchdb:
    image: couchdb:2
    ports:
      - "59840:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    restart: always
    volumes:
      - ./data/couchdb_data:/opt/couchdb/data
      - ./data/cdbdump-kayak.json:/tmp/backup.json
      - ./data/init.sh:/init.sh