version: "3.9"
services:
  app:
    image: kayak-web
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - couchdb
    ports:
      - "12321:80"
    restart: always
  couchdb:
    image: couchdb:2
    ports:
      - "59840:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    restart: always
    volumes:
      - couchdb_data:/opt/couchdb/data
volumes:
  couchdb_data: